name: Tests

on: [push, pull_request]

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo check
        run: cargo check --tests --workspace --benches

  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # Clean unnecessary files to save disk space
      - name: clean unnecessary files to save space
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
          sudo apt -y autoremove --purge
          sudo apt -y autoclean
          sudo apt clean
          rm --recursive --force "$AGENT_TOOLSDIRECTORY"
          df -h          

          # remove large packages manually (all but llvm)
          sudo apt-get remove -y '^aspnetcore-.*' || echo "::warning::The command [sudo apt-get remove -y '^aspnetcore-.*'] failed to complete successfully. Proceeding..."
          sudo apt-get remove -y '^dotnet-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^dotnet-.*' --fix-missing] failed to complete successfully. Proceeding..."
          sudo apt-get remove -y 'php.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y 'php.*' --fix-missing] failed to complete successfully. Proceeding..."
          sudo apt-get remove -y '^mongodb-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^mongodb-.*' --fix-missing] failed to complete successfully. Proceeding..."
          sudo apt-get remove -y '^mysql-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^mysql-.*' --fix-missing] failed to complete successfully. Proceeding..."
          sudo apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri --fix-missing || echo "::warning::The command [sudo apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri --fix-missing] failed to complete successfully. Proceeding..."
          sudo apt-get remove -y google-cloud-sdk --fix-missing || echo "::debug::The command [sudo apt-get remove -y google-cloud-sdk --fix-missing] failed to complete successfully. Proceeding..."
          sudo apt-get remove -y google-cloud-cli --fix-missing || echo "::debug::The command [sudo apt-get remove -y google-cloud-cli --fix-missing] failed to complete successfully. Proceeding..."
          sudo apt-get autoremove -y || echo "::warning::The command [sudo apt-get autoremove -y] failed to complete successfully. Proceeding..."
          sudo apt-get clean || echo "::warning::The command [sudo apt-get clean] failed to complete successfully. Proceeding..."
          df -h          

      # Free up disk space on Ubuntu
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # This might remove tools that are actually needed, if set to "true" but frees about 6 GB
          tool-cache: false

          # large packages, except llvm, are removed manually during the previous step
          # see: https://github.com/jlumbroso/free-disk-space/issues/6
          # TODO: use the discussed whitelist feature when available
          large-packages: false

          swap-storage: true

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Fix CRLF on Windows
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf false

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Set up cache
        uses: Swatinem/rust-cache@v2
      
      - name: Install cargo-nextest
        run: cargo install cargo-nextest

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo build sparkled
        run: cargo build --bin sparkled --release --workspace --all --tests --benches

      - name: Run cargo build sparkle
        run: cargo build --bin sparkle --release --workspace --all --tests --benches

      - name: Run cargo build kasplex
        run: cargo build --bin kasplex --release --workspace --all --tests --benches

      - name: Run cargo test regular features
        run: cargo nextest run --release --workspace

      - name: Run cargo doc tests
        run: cargo test --doc --release --workspace

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --workspace --all-targets --tests --benches -- -D warnings

      - name: Run cargo clippy (WASM32)
        run: cargo clippy --workspace --all --target wasm32-unknown-unknown

  wasm32:
    name: Building WASM32 SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Environment
        shell: bash
        run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install llvm
        id: install_llvm
        continue-on-error: true
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo apt-get install -y clang-15 lldb-15 lld-15 clangd-15 clang-tidy-15 clang-format-15 clang-tools-15 llvm-15-dev lld-15 lldb-15 llvm-15-tools libomp-15-dev libc++-15-dev libc++abi-15-dev libclang-common-15-dev libclang-15-dev libclang-cpp15-dev libunwind-15-dev
          # Make Clang 15 default
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/lib/llvm-15/bin/clang++ 100
          sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-15/bin/clang 100
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/lib/llvm-15/bin/clang-format 100
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/lib/llvm-15/bin/clang-tidy 100
          sudo update-alternatives --install /usr/bin/run-clang-tidy run-clang-tidy /usr/lib/llvm-15/bin/run-clang-tidy 100
          # Alias cc to clang
          sudo update-alternatives --install /usr/bin/cc cc /usr/lib/llvm-15/bin/clang 0
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/lib/llvm-15/bin/clang++ 0

      - name: Install gcc-multilib
        # gcc-multilib allows clang to find gnu libraries properly
        run: |
          sudo apt-get update
          sudo apt install -y gcc-multilib

      - name: Install stable toolchain
        if: steps.install_llvm.outcome == 'success' && steps.install_llvm.conclusion == 'success'
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo install wasm-pack and trunk
        run: |
          cargo install wasm-pack

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NodeJS dependencies
        run: npm install --global typedoc typescript

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # - name: Run cargo check for wasm32 target
      #   run: cargo clippy --target wasm32-unknown-unknown
      - name: Build WASM SDK release
        run: |
          cd wasm && bash build-release
          mv wasm/release/sparkle-wasm32-sdk.zip wasm/release/sparkle-wasm32-sdk-${{ env.SHORT_SHA }}.zip

      - name: Upload WASM build to GitHub 
        uses: actions/upload-artifact@v4
        with: 
          name: sparkle-wasm32-sdk-${{ env.SHORT_SHA }}.zip
          path: wasm/release/sparkle-wasm32-sdk-${{ env.SHORT_SHA }}.zip

  build-release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: Building ${{ matrix.os }}
    steps:
      - name: Fix CRLF on Windows
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf false

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Environment
        shell: bash
        run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build on Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          cargo build --bin sparkled --release
          cargo build --bin sparkle --release
          cargo build --bin kasplex --release
          mkdir sparkle-${{ env.SHORT_SHA }}-windows-x64 || true
          cp target/release/sparkle.exe sparkle-${{ env.SHORT_SHA }}-windows-x64/sparkle.exe
          archive="sparkle-${{ env.SHORT_SHA }}-windows-x64/sparkle-${{ env.SHORT_SHA }}-windows-x64.zip"
          powershell "Compress-Archive sparkle-${{ env.SHORT_SHA }}-windows-x64/* \"${archive}\""

      - name: Upload Windows build to GitHub 
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with: 
          name: sparkle-${{ env.SHORT_SHA }}-windows-x64.zip
          path: sparkle-${{ env.SHORT_SHA }}-windows-x64/sparkle-${{ env.SHORT_SHA }}-windows-x64.zip

      - name: Build on MacOS
        if: runner.os == 'macOS'
        run: |
          cargo build --bin sparkled --release
          cargo build --bin sparkle --release
          cargo build --bin kasplex --release
          mkdir sparkle-${{ env.SHORT_SHA }}-macos-arm64 || true
          cp target/release/sparkle sparkle-${{ env.SHORT_SHA }}-macos-arm64/
          archive="sparkle-${{ env.SHORT_SHA }}-macos-arm64/sparkle-${{ env.SHORT_SHA }}-macos-arm64.zip"
          zip -r "${archive}" ./sparkle-${{ env.SHORT_SHA }}-macos-arm64/*

      - name: Upload MacOS build to GitHub 
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with: 
          name: sparkle-${{ env.SHORT_SHA }}-macos-arm64.zip
          path: sparkle-${{ env.SHORT_SHA }}-macos-arm64/sparkle-${{ env.SHORT_SHA }}-macos-arm64.zip

      - name: Build on Linux
        if: runner.os == 'Linux'
        run: |
          cargo build --bin sparkled --release
          cargo build --bin sparkle --release
          cargo build --bin kasplex --release
          mkdir -p .debpkg/usr/bin
          cp target/release/sparkled .debpkg/usr/bin/
          cp target/release/sparkle .debpkg/usr/bin/
          cp target/release/kasplex .debpkg/usr/bin/
          mkdir sparkle-${{ env.SHORT_SHA }}-linux-gnu-amd64 || true
          cp target/release/sparkle sparkle-${{ env.SHORT_SHA }}-linux-gnu-amd64/
          archive="sparkle-${{ env.SHORT_SHA }}-linux-gnu-amd64/sparkle-${{ env.SHORT_SHA }}-linux-gnu-amd64.zip"
          zip -r "${archive}" ./sparkle-${{ env.SHORT_SHA }}-linux-gnu-amd64/*

      - name: Upload Linux build to GitHub 
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with: 
          name: sparkle-${{ env.SHORT_SHA }}-linux-gnu-amd64.zip
          path: sparkle-${{ env.SHORT_SHA }}-linux-gnu-amd64/sparkle-${{ env.SHORT_SHA }}-linux-gnu-amd64.zip

      - name: Package Debian Release
        if: runner.os == 'Linux'
        id: package_debian
        uses: jiro4989/build-deb-action@v3
        with:
          package: sparkle
          package_root: .debpkg
          maintainer: ASPECTRON
          version: "refs/tags/v0.0.1" # refs/tags/v*.*.*
          arch: 'amd64'
          desc: 'Sparkle for Kaspa BlockDAG'
      - name: Install and Test Debian Package
        if: runner.os == 'Linux'
        run: |
          sudo dpkg -i "${{ steps.package_debian.outputs.file_name }}"
          sparkled --version || echo "Failed to execute sparkled --version"
          sparkle --version || echo "Failed to execute sparkle --version"
          kasplex --version || echo "Failed to execute kasplex --version"

